name: Spring Boot CI

on:
  push:
    branches: [ "main" ] # main 브랜치에 푸시될 때 CI를 실행합니다.
  pull_request:
    branches: [ "main" ] # main 브랜치로 풀 리퀘스트가 올라올 때 CI를 실행합니다.

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    strategy:
      max-parallel: 4

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        architecture: x64

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Run Tests
      run: ./gradlew test
